name: 'your_dbt'
version: '1.0.0'

profile: 'your_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypipe_dbt:
    btc_welldown:
      +materialized: table
    eth_welldown:
      +materialized: table
    market_volume:
      +materialized: table