your_dbt:
  outputs:
    dev:
      dataset: your_data
      job_execution_timeout_seconds: 60
      job_retries: 1
      keyfile: /home/airflow/gcs/data/auth/your-sa-key.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: yourprojectid
      threads: 2
      type: bigquery
  target: dev